// Mock data service for demo mode
export const mockDataService = {
  // Patient mock data
  patientData: {
    appointments: [
      {
        id: 'demo-apt-1',
        patient_id: 'demo-user',
        psychologist_id: 'demo-psych-1',
        scheduled_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
        duration_minutes: 50,
        status: 'confirmed',
        session_notes: null,
        patient_notes: null,
        meeting_link: 'https://meet.google.com/demo-link',
        payment_status: 'pending',
        amount: 200,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        psychologist: {
          id: 'demo-psych-1',
          full_name: 'Dr. André Silva',
          avatar_url: null,
        },
      },
      {
        id: 'demo-apt-2',
        patient_id: 'demo-user',
        psychologist_id: 'demo-psych-1',
        scheduled_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        duration_minutes: 50,
        status: 'completed',
        session_notes: 'Sessão muito produtiva',
        patient_notes: null,
        meeting_link: null,
        payment_status: 'paid',
        amount: 200,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        psychologist: {
          id: 'demo-psych-1',
          full_name: 'Dr. André Silva',
          avatar_url: null,
        },
      },
      {
        id: 'demo-apt-3',
        patient_id: 'demo-user',
        psychologist_id: 'demo-psych-1',
        scheduled_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        duration_minutes: 50,
        status: 'completed',
        session_notes: null,
        patient_notes: null,
        meeting_link: null,
        payment_status: 'paid',
        amount: 200,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        psychologist: {
          id: 'demo-psych-1',
          full_name: 'Dr. André Silva',
          avatar_url: null,
        },
      },
    ],
    myPsychologist: {
      id: 'demo-psych-rel-1',
      patient_id: 'demo-user',
      psychologist_id: 'demo-psych-1',
      status: 'active',
      started_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
      created_at: new Date().toISOString(),
      psychologist: {
        id: 'demo-psych-1',
        full_name: 'Dr. André Silva',
        email: 'andre.silva@psiqueia.com',
        avatar_url: null,
        user_type: 'psychologist',
      },
      psychologist_profile: {
        crp: '06/12345',
        specializations: ['Terapia Cognitivo-Comportamental', 'Ansiedade', 'Depressão'],
        bio: 'Psicólogo clínico com 10 anos de experiência em TCC',
        session_price: 200,
        rating: 4.9,
        total_sessions: 350,
      },
    },
    activeTreatmentPlan: {
      id: 'demo-plan-1',
      patient_id: 'demo-user',
      psychologist_id: 'demo-psych-1',
      plan_name: 'Tratamento para Ansiedade',
      description: 'Plano focado em técnicas de TCC para manejo de ansiedade',
      goals: ['Reduzir episódios de ansiedade', 'Melhorar qualidade do sono', 'Desenvolver técnicas de relaxamento'],
      strategies: ['Terapia Cognitivo-Comportamental', 'Mindfulness', 'Exercícios de respiração'],
      frequency: 'Semanal',
      duration_weeks: 8,
      status: 'active',
      start_date: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
      end_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    diaryEntries: [
      {
        id: 'demo-diary-1',
        patient_id: 'demo-user',
        entry_date: new Date().toISOString(),
        mood: 'good',
        mood_intensity: 7,
        emotions: ['Calmo', 'Esperançoso'],
        content: 'Hoje foi um dia produtivo. Consegui aplicar as técnicas de respiração.',
        attachments: [],
        is_shared: true,
        shared_with: 'demo-psych-1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'demo-diary-2',
        patient_id: 'demo-user',
        entry_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        mood: 'neutral',
        mood_intensity: 5,
        emotions: ['Ansioso', 'Esperançoso'],
        content: 'Dia desafiador, mas consegui me manter calmo.',
        attachments: [],
        is_shared: false,
        shared_with: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    sharedDocuments: [
      {
        id: 'demo-doc-1',
        psychologist_id: 'demo-psych-1',
        patient_id: 'demo-user',
        google_drive_id: 'demo-drive-id-1',
        file_name: 'Plano de Tratamento - Dezembro 2024.pdf',
        file_type: 'application/pdf',
        file_size: 245000,
        drive_url: 'https://drive.google.com/file/demo-1',
        thumbnail_url: null,
        description: 'Plano de tratamento revisado com novas estratégias',
        shared_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        psychologist: {
          id: 'demo-psych-1',
          full_name: 'Dr. André Silva',
          avatar_url: null,
        },
      },
      {
        id: 'demo-doc-2',
        psychologist_id: 'demo-psych-1',
        patient_id: 'demo-user',
        google_drive_id: 'demo-drive-id-2',
        file_name: 'Exercícios de Mindfulness.pdf',
        file_type: 'application/pdf',
        file_size: 180000,
        drive_url: 'https://drive.google.com/file/demo-2',
        thumbnail_url: null,
        description: 'Exercícios práticos para ansiedade',
        shared_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        psychologist: {
          id: 'demo-psych-1',
          full_name: 'Dr. André Silva',
          avatar_url: null,
        },
      },
    ],
  },

  // Psychologist mock data
  psychologistData: {
    appointments: [
      {
        id: 'demo-apt-psych-1',
        patient_id: 'demo-patient-1',
        psychologist_id: 'demo-user',
        scheduled_at: new Date().toISOString(),
        duration_minutes: 50,
        status: 'confirmed',
        session_notes: null,
        patient_notes: null,
        meeting_link: 'https://meet.google.com/demo-1',
        payment_status: 'pending',
        amount: 200,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        patient: {
          id: 'demo-patient-1',
          full_name: 'Maria Silva',
          avatar_url: null,
        },
      },
      {
        id: 'demo-apt-psych-2',
        patient_id: 'demo-patient-2',
        psychologist_id: 'demo-user',
        scheduled_at: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
        duration_minutes: 50,
        status: 'confirmed',
        session_notes: null,
        patient_notes: null,
        meeting_link: 'https://meet.google.com/demo-2',
        payment_status: 'pending',
        amount: 200,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        patient: {
          id: 'demo-patient-2',
          full_name: 'João Santos',
          avatar_url: null,
        },
      },
      {
        id: 'demo-apt-psych-3',
        patient_id: 'demo-patient-3',
        psychologist_id: 'demo-user',
        scheduled_at: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
        duration_minutes: 50,
        status: 'confirmed',
        session_notes: null,
        patient_notes: null,
        meeting_link: 'https://meet.google.com/demo-3',
        payment_status: 'pending',
        amount: 200,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        patient: {
          id: 'demo-patient-3',
          full_name: 'Ana Costa',
          avatar_url: null,
        },
      },
    ],
    myPatients: [
      {
        id: 'demo-patient-rel-1',
        patient_id: 'demo-patient-1',
        psychologist_id: 'demo-user',
        status: 'active',
        started_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date().toISOString(),
        patient: {
          id: 'demo-patient-1',
          full_name: 'Maria Silva',
          avatar_url: null,
          phone: '+55 11 98765-4321',
          birth_date: '1990-05-15',
        },
      },
      {
        id: 'demo-patient-rel-2',
        patient_id: 'demo-patient-2',
        psychologist_id: 'demo-user',
        status: 'active',
        started_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date().toISOString(),
        patient: {
          id: 'demo-patient-2',
          full_name: 'João Santos',
          avatar_url: null,
          phone: '+55 11 97654-3210',
          birth_date: '1985-08-20',
        },
      },
      {
        id: 'demo-patient-rel-3',
        patient_id: 'demo-patient-3',
        psychologist_id: 'demo-user',
        status: 'active',
        started_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date().toISOString(),
        patient: {
          id: 'demo-patient-3',
          full_name: 'Ana Costa',
          avatar_url: null,
          phone: '+55 11 96543-2109',
          birth_date: '1995-12-10',
        },
      },
    ],
    financialStats: {
      monthlyRevenue: 8400,
      totalRevenue: 42000,
      pendingRevenue: 1200,
    },
    transactions: [
      {
        id: 'demo-trans-1',
        psychologist_id: 'demo-user',
        patient_id: 'demo-patient-1',
        appointment_id: 'demo-apt-psych-1',
        transaction_type: 'payment',
        amount: 200,
        currency: 'BRL',
        status: 'completed',
        stripe_payment_id: null,
        stripe_payout_id: null,
        description: 'Sessão de terapia - Maria Silva',
        transaction_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
      {
        id: 'demo-trans-2',
        psychologist_id: 'demo-user',
        patient_id: 'demo-patient-2',
        appointment_id: 'demo-apt-psych-2',
        transaction_type: 'payment',
        amount: 200,
        currency: 'BRL',
        status: 'pending',
        stripe_payment_id: null,
        stripe_payout_id: null,
        description: 'Sessão de terapia - João Santos',
        transaction_date: new Date().toISOString(),
        created_at: new Date().toISOString(),
      },
    ],
    sharedDocuments: [
      {
        id: 'demo-doc-1',
        psychologist_id: 'demo-psych-1',
        patient_id: 'demo-user',
        google_drive_id: 'demo-drive-id-1',
        file_name: 'Plano de Tratamento - Dezembro 2024.pdf',
        file_type: 'application/pdf',
        file_size: 245000,
        drive_url: 'https://drive.google.com/file/demo-1',
        thumbnail_url: null,
        description: 'Plano de tratamento revisado com novas estratégias',
        shared_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        psychologist: {
          id: 'demo-psych-1',
          full_name: 'Dr. André Silva',
          avatar_url: null,
        },
      },
      {
        id: 'demo-doc-2',
        psychologist_id: 'demo-psych-1',
        patient_id: 'demo-user',
        google_drive_id: 'demo-drive-id-2',
        file_name: 'Exercícios de Mindfulness.pdf',
        file_type: 'application/pdf',
        file_size: 180000,
        drive_url: 'https://drive.google.com/file/demo-2',
        thumbnail_url: null,
        description: 'Exercícios práticos para ansiedade',
        shared_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        psychologist: {
          id: 'demo-psych-1',
          full_name: 'Dr. André Silva',
          avatar_url: null,
        },
      },
    ],
    sharedDocuments: [
      {
        id: 'demo-doc-psych-1',
        psychologist_id: 'demo-user',
        patient_id: 'demo-patient-1',
        google_drive_id: 'demo-drive-id-psych-1',
        file_name: 'Protocolo TCC - Maria Silva.pdf',
        file_type: 'application/pdf',
        file_size: 320000,
        drive_url: 'https://drive.google.com/file/demo-psych-1',
        thumbnail_url: null,
        description: 'Protocolo de TCC personalizado',
        shared_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        patient: {
          id: 'demo-patient-1',
          full_name: 'Maria Silva',
          avatar_url: null,
        },
      },
      {
        id: 'demo-doc-psych-2',
        psychologist_id: 'demo-user',
        patient_id: 'demo-patient-2',
        google_drive_id: 'demo-drive-id-psych-2',
        file_name: 'Diário de Pensamentos.pdf',
        file_type: 'application/pdf',
        file_size: 150000,
        drive_url: 'https://drive.google.com/file/demo-psych-2',
        thumbnail_url: null,
        description: 'Template para registro de pensamentos',
        shared_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        patient: {
          id: 'demo-patient-2',
          full_name: 'João Santos',
          avatar_url: null,
        },
      },
    ],
  },
};
